// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GloboChallenge.Zaap.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Zaap")]
    [NUnit.Framework.CategoryAttribute("Chrome")]
    public partial class ZaapFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Zaap.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Zaap", null, ProgrammingLanguage.CSharp, new string[] {
                        "Chrome"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Acessar o Zaap")]
        public virtual void AcessarOZaap()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acessar o Zaap", null, ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("que eu acesso o Zaap", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 9
 testRunner.And("esteja logado com perfil Operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.And("conecto em uma equipe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.Then("estarei na pagina inicial do Operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por Nome")]
        [NUnit.Framework.TestCaseAttribute("\"LARISSA A DO NASCIMENTO\"", null)]
        public virtual void PesquisarClientePorNome(string nome, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por Nome", null, exampleTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 14
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 15
 testRunner.And(string.Format("realizo uma busca por nome {0}", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 16
 testRunner.Then(string.Format("encontro o {0} com sucesso", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por Código de Identificação")]
        [NUnit.Framework.TestCaseAttribute("\"22109\"", "\"ALDENEIDE APARECIDA AMARANTE LIRA\"", null)]
        public virtual void PesquisarClientePorCodigoDeIdentificacao(string codigoDeIdentificacao, string nome, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por Código de Identificação", null, exampleTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 24
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 25
 testRunner.And(string.Format("realizo uma busca por {0}", codigoDeIdentificacao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.Then(string.Format("encontro o {0} com sucesso", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por Cpf/CNPJ")]
        [NUnit.Framework.TestCaseAttribute("\"2567929762\"", null)]
        public virtual void PesquisarClientePorCpfCNPJ(string cPF, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por Cpf/CNPJ", null, exampleTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 33
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 34
 testRunner.And(string.Format("realizo uma busca por cpf {0}", cPF), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 35
 testRunner.Then("a pesquisa é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por Contrato")]
        [NUnit.Framework.TestCaseAttribute("\"01PRE000886904 PRE\"", null)]
        public virtual void PesquisarClientePorContrato(string contrato, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por Contrato", null, exampleTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 44
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 45
 testRunner.And(string.Format("realizo uma busca por Contrato {0}", contrato), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 46
 testRunner.Then("a pesquisa é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("pesquisar cliente por complemento do contrato")]
        [NUnit.Framework.TestCaseAttribute("\"15436906\"", null)]
        public virtual void PesquisarClientePorComplementoDoContrato(string complementoDoContrato, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("pesquisar cliente por complemento do contrato", null, exampleTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 53
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 54
 testRunner.And(string.Format("realizo uma busca por ComplementoDoContrato {0}", complementoDoContrato), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 55
 testRunner.Then("a pesquisa é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por E-mail")]
        [NUnit.Framework.TestCaseAttribute("\"adriana.braga@teste.com\"", null)]
        public virtual void PesquisarClientePorE_Mail(string email, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por E-mail", null, exampleTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 62
testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 63
 testRunner.And(string.Format("realizo uma busca por Email {0}", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 64
 testRunner.Then("a pesquisa é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar cliente por Telefone")]
        [NUnit.Framework.TestCaseAttribute("\"37541156\"", null)]
        public virtual void PesquisarClientePorTelefone(string telefone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar cliente por Telefone", null, exampleTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 71
 testRunner.When("que esteja com perfil de operador", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 72
 testRunner.And(string.Format("realizo uma busca por Telefone {0}", telefone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 73
 testRunner.Then("a pesquisa é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inativar e-mail")]
        public virtual void InativarE_Mail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inativar e-mail", null, ((string[])(null)));
#line 79
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 80
 testRunner.Given("que realizo uma busca por cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 81
 testRunner.When("seleciono a opção de email inativo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 82
 testRunner.Then("o email é inativado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Alterar Telefone")]
        public virtual void AlterarTelefone()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar Telefone", null, ((string[])(null)));
#line 85
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 86
 testRunner.Given("que realizo uma busca por cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 87
 testRunner.And("seleciono a opção editar Telefone", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 88
 testRunner.When("incluo as informações que desejo alterar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 89
 testRunner.Then("o Telefone é alterado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Acessar a tela de negociação")]
        public virtual void AcessarATelaDeNegociacao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acessar a tela de negociação", null, ((string[])(null)));
#line 91
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 92
 testRunner.Given("que realizo uma busca por cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 93
 testRunner.And("seleciono cliente por Nome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 94
 testRunner.Then("acesso a tela de negociação com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("listar boletos")]
        public virtual void ListarBoletos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("listar boletos", null, ((string[])(null)));
#line 96
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 97
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 98
 testRunner.When("seleciono a opção boletos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 99
 testRunner.Then("acesso a lista de boletos com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reimpressão de boleto")]
        public virtual void ReimpressaoDeBoleto()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reimpressão de boleto", null, ((string[])(null)));
#line 101
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 102
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 103
 testRunner.When("seleciono a opção boletos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 104
 testRunner.Then("a reimpressão é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inserção de ocorrência Nulo")]
        public virtual void InsercaoDeOcorrenciaNulo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inserção de ocorrência Nulo", null, ((string[])(null)));
#line 106
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 107
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 108
 testRunner.When("incluo uma nova ocorrência em Nulo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 109
 testRunner.Then("a ocorrência é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inserção de ocorrência em Andamento")]
        public virtual void InsercaoDeOcorrenciaEmAndamento()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inserção de ocorrência em Andamento", null, ((string[])(null)));
#line 111
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 112
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 113
 testRunner.When("incluo uma nova ocorrência em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 114
 testRunner.Then("a ocorrência é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inserção de ocorrência Agendado")]
        public virtual void InsercaoDeOcorrenciaAgendado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inserção de ocorrência Agendado", null, ((string[])(null)));
#line 116
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 117
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 118
 testRunner.When("incluo uma nova ocorrência em agendamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 119
 testRunner.Then("a ocorrência é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inserção de serviço")]
        public virtual void InsercaoDeServico()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inserção de serviço", null, ((string[])(null)));
#line 121
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 122
 testRunner.Given("que realizo uma busca por cliente que tenha feito negociacao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 123
 testRunner.When("incluo um novo serviço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 124
 testRunner.Then("a ocorrência é realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
